# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c018d70facdeffc3f266de6da262f518ba2e5c631e761587857828ee3f014535dca463c1d83c8ce1db5624825e05c92bf751b33b2359e2aa1f4d882746810e8

test:
  secret_key_base: b8e74d22bb584609bc36996ea077815b315ef746ac4c7e93883a163b926e254d94e266c2664f485f0659de505f50f1f13e7719f570429cd871e3567ad9c2823c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
